/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package theredchessboard;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(1+1, "1+1 should equal 2");
    }
}
